# Generated by Django 3.2.4 on 2021-06-25 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('idTipo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de tipo')),
                ('nombreTipo', models.CharField(max_length=50, verbose_name='Nombre de Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de persona')),
                ('Rut', models.CharField(max_length=12, verbose_name='rut')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de persona')),
                ('apellido', models.CharField(max_length=50, verbose_name='apellido de persona')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipo')),
            ],
        ),
    ]
